### ISSUE TITLE
Acesso ao ITVP - EBC

### ISSUE THREAD

**Issue by comunicaticket** [ticketcomunica/chamados#22]
**Aberto por:**

 >Max Oliveira

**Setor:** 

>Operação 

--- 

Erro tentando baixar arquivos do PRODAV.
ERR_CONNECTION_TIMED_OUT

**Comment by alyssonmonteiro** [comment]
Foi aberto um chamado junto a Sinfo para a resolução do problema.

Aguardando retorno.

**Comment by alyssonmonteiro** [comment]
Liberação realizada pela Sinfo.
